# Generated by Django 5.1.1 on 2024-10-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0002_alter_worldcities_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldcities',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
